# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "jinluzhang1126"
repo_name: "arxiv-papers"
show_authors: True
show_links: True
show_badge: False
max_results: 20

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    # --------- My Keywords ---------
    "Interaction":
        filters: ["Human Scene Interaction", "Human Object Interaction","Human-Scene Interaction", "Human-Object Interaction"]
    "World Model":
        filters: ["World Model", "Interactive Video Generation", "Interactive World Model", "world foundation model", "Physical World Model"]
    "VLM":
        filters: ["Vision Language Model", "Vision Language Models", "Vision-Language Model", "Vision-Language Models"]
    "VLA":
        filters: ["Vision Language Action","Vision-Language-Action"]
    "Humanoid":
        filters: ["Humanoid Robot", "Humanoid"]
    "3DGS/NeRF":
        filters: ["NeRF", "Gaussian Splatting"]
